#include "../includes/ft_printf.h"
#include <stdio.h>

int		main()
{
//	int   sum = 0;
//	char *arr = "HelloWorlHelloWorlHelloWorlHelloWorlHelloWorlHelloWorlHelloWorlHelloWorlHelloWorlHelloWorlHelloWorlHelloWorlHelloWorl";
//	long int x = 9223372036854775808;
	double x = -3.3;

//	printf("%li\n",y);
  	ft_printf("ft_printf\t\t||%f|\n", x);
	printf("printf\t\t\t||%f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%15f|\n", x);
	printf("printf\t\t\t||%15f|\n", x);
 	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%-15f|\n", x);
	printf("printf\t\t\t||%-15f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%- .15f|\n", x);
	printf("printf\t\t\t||%- .15f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%-0.15f|\n", x);
	printf("printf\t\t\t||%-0.15f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%-025.15f|\n", x);
	printf("printf\t\t\t||%-025.15f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%030.7f|\n", x);
	printf("printf\t\t\t||%030.7f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%0-25.6f|\n", x);
	printf("printf\t\t\t||%0-25.6f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%0+10.14f|\n", x);
	printf("printf\t\t\t||%0+10.14f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%0+15.6f|\n", x);
	printf("printf\t\t\t||%0+15.6f|\n", x);
 	printf("====================================================\n");
	ft_printf("ft_printf\t\t||% 0.9f|\n", x);
	printf("printf\t\t\t||% 0.9f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%+08f|\n", x);
	printf("printf\t\t\t||%+08f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%+8f|\n", x);
	printf("printf\t\t\t||%+8f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%0 .6f|\n", x);
	printf("printf\t\t\t||%0 .6f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||% +7.9f|\n", x);
	printf("printf\t\t\t||% +7.9f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||% +7.6f|\n", x);
	printf("printf\t\t\t||% +7.6f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%+7.9f|\n", x);
	printf("printf\t\t\t||%+7.9f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%+07.6f|\n", x);
	printf("printf\t\t\t||%+07.6f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%+0f|\n", x);
	printf("printf\t\t\t||%+0f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%0.9f|\n", x);
	printf("printf\t\t\t||%0.9f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%07.6f|\n", x);
	printf("printf\t\t\t||%07.6f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%07.9f|\n", x);
	printf("printf\t\t\t||%07.9f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%0f|\n", x);
	printf("printf\t\t\t||%0f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%9.7f|\n", x);
	printf("printf\t\t\t||%9.7f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%9.17f|\n", x);
	printf("printf\t\t\t||%9.17f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%9.34f|\n", x);
	printf("printf\t\t\t||%9.34f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%9.33f|\n", x);
	printf("printf\t\t\t||%9.33f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%9.32f|\n", x);
	printf("printf\t\t\t||%9.32f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%9.31f|\n", x);
	printf("printf\t\t\t||%9.31f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%9.30f|\n", x);
	printf("printf\t\t\t||%9.30f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%9.22f|\n", x);
	printf("printf\t\t\t||%9.22f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%9.26f|\n", x);
	printf("printf\t\t\t||%9.26f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%9.27f|\n", x);
	printf("printf\t\t\t||%9.27f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%9.28f|\n", x);
	printf("printf\t\t\t||%9.28f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%9.50f|\n", x);
	printf("printf\t\t\t||%9.50f|\n", x);
	printf("====================================================\n");
	ft_printf("ft_printf\t\t||%9.80f|\n", x);
	printf("printf\t\t\t||%9.80f|\n", x);

/*   	ft_printf("%li|\n", x);
	ft_printf("%15li|\n", x);
	ft_printf("%-15li|\n", x);
	ft_printf("%- .15li|\n", x);
	ft_printf("%-0.15li|\n", x);
	ft_printf("%-025.15li|\n", x);
	ft_printf("%030.7li|\n", x);
	ft_printf("%0-25.6li|\n", x);
	ft_printf("%0+10.14li|\n", x);
	ft_printf("%0+15.6li|\n", x);
	ft_printf("% 0.9li|\n", x);
	ft_printf("%+08li|\n", x);
	ft_printf("%+8li|\n", x);
	ft_printf("%0 .6li|\n", x);
	ft_printf("% +7.9li|\n", x);
	ft_printf("% +7.6li|\n", x);
	ft_printf("%+7.9li|\n", x);
	ft_printf("%+07.6li|\n", x);
	ft_printf("%+0li|\n", x);
	ft_printf("%0.9li|\n", x);
	ft_printf("%07.6li|\n", x);
	ft_printf("%07.9li|\n", x);
	ft_printf("%0li|\n", x);
	ft_printf("%9.7li|\n", x);
	ft_printf("%9.11li|\n", x); */

	// ft_printf("%-#7i|\n", x);
	// ft_printf("%-07i|\n", x);
	// ft_printf("%-7i|\n", x);
	// ft_printf("%#9.5i|\n", x); 
	// ft_printf("%-#9i|\n", x);
	// ft_printf("%-7.5i|\n", x);
	// ft_printf("%-#.5i|\n", x); 
	// ft_printf("%-#6i|\n", x);
 	// ft_printf("%#9.9i|\n", x);
	// ft_printf("%7.12i|\n", x);
	// ft_printf("%#7.12i|\n", x);
	// ft_printf("%#6.9i|\n", x);
	// ft_printf("%0#9i|\n", x);
	// ft_printf("%0-7.5i|\n", x);
	// ft_printf("%-0.5i|\n", x);
	// ft_printf("%0#15i|\n", x);
	// ft_printf("%0#3i|\n", x);
 	// ft_printf("%0#6i|\n", x); 
 	// ft_printf("%0#9.9i|\n", x);
	// ft_printf("%07.12i|\n", x);
	// ft_printf("%0#7.12i|\n", x);
	// ft_printf("%-0#6.9i|\n", x);
 	// ft_printf("%0#4.9i|\n", x);
	// ft_printf("%0-7.5i|\n", x);
	// ft_printf("%-0.5i|\n", x);
	// ft_printf("%0#15.5i|\n", x);
	// ft_printf("%09.5i|\n", x);
	// ft_printf("%07.12i|\n", x);
	// ft_printf("%0#7.12i|\n", x);
 	// ft_printf("%-0#6.9i|\n", x);
 	// ft_printf("%0#4.9i|\n", x);
	// ft_printf("%0#9.4i|\n", x);
	// ft_printf("% #9.4i|\n", x);
	// ft_printf("% 9.4i|\n", x);
	// ft_printf("%9.4i|\n", x);
	// ft_printf("%9.7i|\n", x);
	// ft_printf("%9.11i|\n", x);
	// ft_printf("%0#9.4i|\n", x);
	// ft_printf("% #9.4i|\n", x);
	// ft_printf("% 9.4i|\n", x);
	// ft_printf("%9.4i|\n", x);
	// ft_printf("%9.7i|\n", x);
	// ft_printf("%9.11i|\n", x);

	printf("====================================================\n");


/*  printf("%i|\n", x);
	printf("%15i|\n", x);
	printf("%-15i|\n", x);
	printf("%- .15i|\n", x);
	printf("%-0.15i|\n", x);
	printf("%-025.15i|\n", x);
	printf("%030.7i|\n", x);
	printf("%0-25.6i|\n", x);
	printf("%0+10.14i|\n", x);
	printf("%0+15.6i|\n", x);
	printf("% 0.9i|\n", x);
	printf("%+08i|\n", x);
	printf("%+8i|\n", x);
	printf("%0 .6i|\n", x);
	printf("% +7.9i|\n", x);
	printf("% +7.6i|\n", x);
	printf("%+7.9i|\n", x);
	printf("%+07.6i|\n", x);
	printf("%+0i|\n", x);
	printf("%0.9i|\n", x);
	printf("%07.6i|\n", x);
	printf("%07.9i|\n", x);
	printf("%0i|\n", x);
	printf("%9.7i|\n", x);
	printf("%9.11i|\n", x);
 */
/*  	printf("%li|\n", x);
	printf("%15li|\n", x);
	printf("%-15li|\n", x);
	printf("%- .15li|\n", x);
	printf("%-0.15li|\n", x);
	printf("%-025.15li|\n", x);
	printf("%030.7li|\n", x);
	printf("%0-25.6li|\n", x);
	printf("%0+10.14li|\n", x);
	printf("%0+15.6li|\n", x);
	printf("% 0.9li|\n", x);
	printf("%+08li|\n", x);
	printf("%+8li|\n", x);
	printf("%0 .6li|\n", x);
	printf("% +7.9li|\n", x);
	printf("% +7.6li|\n", x);
	printf("%+7.9li|\n", x);
	printf("%+07.6li|\n", x);
	printf("%+0li|\n", x);
	printf("%0.9li|\n", x);
	printf("%07.6li|\n", x);
	printf("%07.9li|\n", x);
	printf("%0li|\n", x);
	printf("%9.7li|\n", x);
	printf("%9.11li|\n", x); */

//	printf("%0 .6i|\n", x);
//	printf("% +7.9i|\n", x);
//	printf("% +7.6i|\n", x);
//	printf("%+7.9i|\n", x);
//	printf("%+07.6i|\n", x);
//	printf("%+0i|\n", x);
//	printf("%0.9i|\n", x);
//	printf("%07.6i|\n", x);
//	printf("%07.9i|\n", x);
//	printf("%0i|\n", x);
//	printf("%i|\n", x);
//	printf("%7i|\n", x);
//	printf("%9.7i|\n", x);
//	printf("%9.11i|\n", x);
//	printf("%-#7i|\n", x);
//	printf("%-07i|\n", x);
//	printf("%-7i|\n", x);
//	printf("%#9.5i|\n", x); 
//	printf("%-#9i|\n", x);
//	printf("%-7.5i|\n", x);
//	printf("%-#.5i|\n", x); 
	// printf("%-#6i|\n", x);
 	// printf("%#9.9i|\n", x);
	// printf("%7.12i|\n", x);
	// printf("%#7.12i|\n", x);
	// printf("%#6.9i|\n", x);
	// printf("%0#9i|\n", x);
	// printf("%0-7.5i|\n", x);
	// printf("%-0.5i|\n", x);
	// printf("%0#15i|\n", x);
	// printf("%0#3i|\n", x);
// 	printf("%0#6i|\n", x); 
 	// printf("%0#9.9i|\n", x);
	// printf("%07.12i|\n", x);
	// printf("%0#7.12i|\n", x);
	// printf("%-0#6.9i|\n", x);
 	// printf("%0#4.9i|\n", x);
	// printf("%0-7.5i|\n", x);
	// printf("%-0.5i|\n", x);
	// printf("%0#15.5i|\n", x);
	// printf("%09.5i|\n", x);
	// printf("%07.12i|\n", x);
	// printf("%0#7.12i|\n", x);
 	// printf("%-0#6.9i|\n", x);
 	// printf("%0#4.9i|\n", x);
	// printf("%0#9.4i|\n", x);
	// printf("% #9.4i|\n", x);
	// printf("% 9.4i|\n", x);
	// printf("%9.4i|\n", x);
	// printf("%9.7i|\n", x);
	// printf("%9.11i|\n", x);
//	printf("%0#9.4i|\n", x);
//	printf("% #9.4i|\n", x);
//	printf("% 9.4i|\n", x);
//	printf("%9.4i|\n", x);
//	printf("%9.7i|\n", x);
//	printf("%9.11i|\n", x);

/*  ft_printf("%-#7X|\n", x);
	ft_printf("%-07X|\n", x);
	ft_printf("%-7X|\n", x);
 	ft_printf("%7X|\n", x);
	ft_printf("%+0x|\n", x);
	ft_printf("%#9.5x|\n", x); 
	ft_printf("%-#9x|\n", x);
	ft_printf("%-7.5x|\n", x);
	ft_printf("%-#.5x|\n", x); 
	ft_printf("%-#6x|\n", x);
 	ft_printf("%#9.9x|\n", x);
	ft_printf("%7.12x|\n", x);
	ft_printf("%#7.12x|\n", x);
	ft_printf("%#6.9x|\n", x);
	ft_printf("%0#9x|\n", x);
	ft_printf("%0-7.5x|\n", x);
	ft_printf("%-0.5x|\n", x);
	ft_printf("%0#15x|\n", x);
	ft_printf("%0#3x|\n", x);
 	ft_printf("%0#6x|\n", x); 
 	ft_printf("%0#9.9x|\n", x);
	ft_printf("%07.12x|\n", x);
	ft_printf("%0#7.12x|\n", x);
	ft_printf("%-0#6.9x|\n", x);
 	ft_printf("%0#4.9x|\n", x);
	ft_printf("%0-7.5x|\n", x);
	ft_printf("%-0.5x|\n", x);
	ft_printf("%0#15.5x|\n", x);
	ft_printf("%09.5x|\n", x);
	ft_printf("%07.12x|\n", x);
	ft_printf("%0#7.12x|\n", x);
 	ft_printf("%-0#6.9x|\n", x);
 	ft_printf("%0#4.9x|\n", x);
	ft_printf("%0#9.4x|\n", x);
	ft_printf("% #9.4x|\n", x);
	ft_printf("% 9.4x|\n", x);
	ft_printf("%9.4x|\n", x);
	ft_printf("%9.7x|\n", x);
	ft_printf("%9.11x|\n", x);
 	ft_printf("%0#9.4x|\n", x);
	ft_printf("% #9.4x|\n", x);
	ft_printf("% 9.4x|\n", x);
	ft_printf("%9.4x|\n", x);
	ft_printf("%9.7x|\n", x);
	ft_printf("%9.11x|\n", x);
	printf("====================================================\n", x);
  	printf("%-#7X|\n", x);
	printf("%-07X|\n", x);
	printf("%-7X|\n", x);
 	printf("%7X|\n", x);
	printf("%+0x|\n", x);
	printf("%#9.5x|\n", x); 
	printf("%-#9x|\n", x);
	printf("%-7.5x|\n", x);
	printf("%-#.5x|\n", x);
	printf("%-#6x|\n", x);
	printf("%#9.9x|\n", x);
	printf("%7.12x|\n", x);
	printf("%#7.12x|\n", x);
	printf("%#6.9x|\n", x);
	printf("%0#9x|\n", x);
	printf("%0-7.5x|\n", x);
	printf("%-0.5x|\n", x);
	printf("%0#15x|\n", x);
	printf("%0#3x|\n", x);
	printf("%0#6x|\n", x);
 	printf("%0#9.9x|\n", x);
	printf("%07.12x|\n", x);
	printf("%0#7.12x|\n", x);
	printf("%-0#6.9x|\n", x);
 	printf("%0#4.9x|\n", x);
	 printf("%0-7.5x|\n", x);
	 printf("%-0.5x|\n", x);
	 printf("%0#15.5x|\n", x);
	 printf("%09.5x|\n", x);
	 printf("%07.12x|\n", x);
	 printf("%0#7.12x|\n", x);
 	printf("%-0#6.9x|\n", x);
 	printf("%0#4.9x|\n", x);
	printf("%0#9.4x|\n", x);
	printf("% #9.4x|\n", x);
	printf("% 9.4x|\n", x);
	printf("%9.4x|\n", x);
	printf("%9.7x|\n", x);
	printf("%9.11x|\n", x);
 	printf("%0#9.4x|\n", x);
	printf("% #9.4x|\n", x);
	printf("% 9.4x|\n", x);
	printf("%9.4x|\n", x);
	printf("%9.7x|\n", x);
	printf("%9.11x|\n", x); */

	
//	printf("%9.4x|\n", x);
//	printf("%9.7x|\n", x);
//	printf("%9.11x|\n", x);

//	sum = ft_printf("%-200.16s|\n", arr);
//	printf("sum = %i|\n", sum);
//	sum = printf("%-200.16s|\n", arr);
//	printf("sum = %i|\n", sum);
//	printf("%-4cf\n", number); 
	return (EXIT_SUCCESS);
}
